import { nanoid } from "nanoid";

export const placeholderCoursesTrading = [
  {
    id: nanoid(),
    title: "COMPLETE FOREX TRADING COURSE AND MY STRATEGY",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "99.99",
  },
];

export const placeholderStockTrading = [
  {
    id: nanoid(),
    title: "Complete Stock Trading Course and Strategies",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "99.99",
  },
  {
    id: nanoid(),
    title: "Advanced Stock Trading Techniques",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "149.99",
  },
  {
    id: nanoid(),
    title: "Options Trading Fundamentals",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "79.99",
  },
  {
    id: nanoid(),
    title: "Swing Trading Strategies for Stocks",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "129.99",
  },
  {
    id: nanoid(),
    title: "Technical Analysis for Stock Market",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "69.99",
  },
  {
    id: nanoid(),
    title: "Dividend Investing",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "89.99",
  },
  {
    id: nanoid(),
    title: "Value Investing Strategies",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "109.99",
  },
  {
    id: nanoid(),
    title: "Stock Market Fundamentals",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "99.99",
  },
  {
    id: nanoid(),
    title: "Stock Portfolio Management",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "119.99",
  },
  {
    id: nanoid(),
    title: "Understanding Stock Charts",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "79.99",
  },
  {
    id: nanoid(),
    title: "Stock Trading on Margin",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "139.99",
  },
  {
    id: nanoid(),
    title: "Stock Market Psychology",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "89.99",
  },
  {
    id: nanoid(),
    title: "High-Frequency Stock Trading",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "159.99",
  },
  {
    id: nanoid(),
    title: "Fundamental Analysis for Stocks",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "69.99",
  },
  {
    id: nanoid(),
    title: "Stock Market Technical Indicators",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "109.99",
  },
  {
    id: nanoid(),
    title: "Algorithmic Stock Trading",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "149.99",
  },
];

export const placeholderCryptoTrading = [
  {
    id: nanoid(),
    title: "Complete Crypto Trading Course and Strategies",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "99.99",
  },
  {
    id: nanoid(),
    title: "Advanced Crypto Trading Techniques",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "149.99",
  },
  {
    id: nanoid(),
    title: "Options Trading Fundamentals in Crypto",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "79.99",
  },
  {
    id: nanoid(),
    title: "Cryptocurrency Trading Strategies",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "129.99",
  },
  {
    id: nanoid(),
    title: "Technical Analysis for Crypto Beginners",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "69.99",
  },
  {
    id: nanoid(),
    title: "Crypto Market Psychology",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "89.99",
  },
  {
    id: nanoid(),
    title: "Crypto Scalping Techniques",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "99.99",
  },
  {
    id: nanoid(),
    title: "Crypto Trend Following Strategies",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "109.99",
  },
  {
    id: nanoid(),
    title: "Analyzing Crypto Charts",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "119.99",
  },
  {
    id: nanoid(),
    title: "Swing Trading Cryptocurrencies",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "129.99",
  },
  {
    id: nanoid(),
    title: "Fundamentals of Blockchain Technology",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "79.99",
  },
  {
    id: nanoid(),
    title: "ICO and Token Sales Strategies",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "139.99",
  },
  {
    id: nanoid(),
    title: "Crypto Portfolio Management",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "149.99",
  },
  {
    id: nanoid(),
    title: "Investing in Altcoins",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "159.99",
  },
  {
    id: nanoid(),
    title: "Crypto Risk Management",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "69.99",
  },
  {
    id: nanoid(),
    title: "Decentralized Finance (DeFi) Overview",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "109.99",
  },
];

export const placeholderCommTrading = [
  {
    id: nanoid(),
    title: "Commodity Trading: A Complete Guide",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "99.99",
  },
  {
    id: nanoid(),
    title: "Advanced Commodity Trading Techniques",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "149.99",
  },
  {
    id: nanoid(),
    title: "Options Trading in Commodities",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "79.99",
  },
  {
    id: nanoid(),
    title: "Commodity Market Analysis Strategies",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "129.99",
  },
  {
    id: nanoid(),
    title: "Technical Analysis for Commodity Markets",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "69.99",
  },
  {
    id: nanoid(),
    title: "Commodities Trading on Margin",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "89.99",
  },
  {
    id: nanoid(),
    title: "Futures Trading in Commodities",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "109.99",
  },
  {
    id: nanoid(),
    title: "Commodity Trading Strategies",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "99.99",
  },
  {
    id: nanoid(),
    title: "Commodity Market Indicators",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "119.99",
  },
  {
    id: nanoid(),
    title: "Risk Management in Commodities",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "79.99",
  },
  {
    id: nanoid(),
    title: "High-Frequency Commodity Trading",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "139.99",
  },
  {
    id: nanoid(),
    title: "Commodity Trading Fundamentals",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "69.99",
  },
  {
    id: nanoid(),
    title: "Trading Agricultural Commodities",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "109.99",
  },
  {
    id: nanoid(),
    title: "Precious Metals Trading Strategies",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "149.99",
  },
  {
    id: nanoid(),
    title: "Energy Commodities Market Analysis",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "89.99",
  },
  {
    id: nanoid(),
    title: "Commodity ETFs and ETNs",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "99.99",
  },
];

export const placeholderRobForexTrading = [
  {
    id: nanoid(),
    title: "Top 5 Algo Trading",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "99.99",
  },

  {
    id: nanoid(),
    title: "Top 5 Scaling Up",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "149.99",
  },
];

export const placeholderRobCryptoTrading = [
  {
    id: nanoid(),
    title: "Crypto Scalping Techniques",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "99.99",
  },
  {
    id: nanoid(),
    title: "Crypto Trend Following Strategies",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "109.99",
  },
  {
    id: nanoid(),
    title: "Analyzing Crypto Charts",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "119.99",
  },
  {
    id: nanoid(),
    title: "Swing Trading Cryptocurrencies",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "129.99",
  },
  {
    id: nanoid(),
    title: "Fundamentals of Blockchain Technology",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "79.99",
  },
  {
    id: nanoid(),
    title: "ICO and Token Sales Strategies",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "139.99",
  },
  {
    id: nanoid(),
    title: "Crypto Portfolio Management",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "149.99",
  },
  {
    id: nanoid(),
    title: "Investing in Altcoins",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "159.99",
  },
  {
    id: nanoid(),
    title: "Crypto Risk Management",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "69.99",
  },
  {
    id: nanoid(),
    title: "Decentralized Finance (DeFi) Overview",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "109.99",
  },
  {
    id: nanoid(),
    title: "Cryptocurrency Mining Essentials",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "129.99",
  },
  {
    id: nanoid(),
    title: "Security Practices for Crypto Trading",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "89.99",
  },
  {
    id: nanoid(),
    title: "Crypto Arbitrage Strategies",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "139.99",
  },
  {
    id: nanoid(),
    title: "NFTs: An Investment Guide",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "99.99",
  },
  {
    id: nanoid(),
    title: "Understanding Smart Contracts",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "149.99",
  },
  {
    id: nanoid(),
    title: "Staking and Yield Farming",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "79.99",
  },
];

export const placeholderRobCommTrading = [
  {
    id: nanoid(),
    title: "Commodity Trading: A Complete Guide",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "99.99",
  },
  {
    id: nanoid(),
    title: "Advanced Commodity Trading Techniques",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "149.99",
  },
  {
    id: nanoid(),
    title: "Options Trading in Commodities",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "79.99",
  },
  {
    id: nanoid(),
    title: "Commodity Market Analysis Strategies",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "129.99",
  },
  {
    id: nanoid(),
    title: "Technical Analysis for Commodity Markets",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "69.99",
  },
  {
    id: nanoid(),
    title: "Commodities Trading on Margin",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "89.99",
  },
  {
    id: nanoid(),
    title: "Futures Trading in Commodities",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "109.99",
  },
  {
    id: nanoid(),
    title: "Commodity Trading Strategies",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "99.99",
  },
  {
    id: nanoid(),
    title: "Commodity Market Indicators",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "119.99",
  },
  {
    id: nanoid(),
    title: "Risk Management in Commodities",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "79.99",
  },
  {
    id: nanoid(),
    title: "High-Frequency Commodity Trading",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "139.99",
  },
  {
    id: nanoid(),
    title: "Commodity Trading Fundamentals",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "69.99",
  },
  {
    id: nanoid(),
    title: "Trading Agricultural Commodities",
    thumbnail: require("../../assets/top-scaling-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "109.99",
  },
  {
    id: nanoid(),
    title: "Precious Metals Trading Strategies",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "149.99",
  },
  {
    id: nanoid(),
    title: "Energy Commodities Market Analysis",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "89.99",
  },
  {
    id: nanoid(),
    title: "Commodity ETFs and ETNs",
    thumbnail: require("../../assets/top-5-trading-robots.jpg"),
    author: "Okeke Chukwuike Christian",
    price: "99.99",
  },
];
